var hierarchy =
[
    [ "microla::geometry::AABB< T >", "structmicrola_1_1geometry_1_1AABB.html", null ],
    [ "microla::fusion::AccelSample< T >", "structmicrola_1_1fusion_1_1AccelSample.html", null ],
    [ "microla::constants::detail::ConstantProxy< T, Fn >", "structmicrola_1_1constants_1_1detail_1_1ConstantProxy.html", null ],
    [ "microla::ConstMatrixView< T, R, C >", "classmicrola_1_1ConstMatrixView.html", null ],
    [ "ConstMatrixView< T, R, C >", "classConstMatrixView_3_01T_00_01R_00_01C_01_4.html", null ],
    [ "microla::ConstVectorView< T, N >", "classmicrola_1_1ConstVectorView.html", null ],
    [ "microla::ExtendedKalmanFilter< T, StateDim, MeasDim >", "classmicrola_1_1ExtendedKalmanFilter.html", null ],
    [ "microla::geometry::Frustum< T >", "structmicrola_1_1geometry_1_1Frustum.html", null ],
    [ "microla::IdentityHelper< T, R, C, Enable >", "structmicrola_1_1IdentityHelper.html", null ],
    [ "microla::fusion::Imu6Sample< T >", "structmicrola_1_1fusion_1_1Imu6Sample.html", null ],
    [ "microla::fusion::Imu9Sample< T >", "structmicrola_1_1fusion_1_1Imu9Sample.html", null ],
    [ "microla::detail::index_sequence< Is >", "structmicrola_1_1detail_1_1index__sequence.html", null ],
    [ "microla::KalmanFilter< T, StateDim, MeasDim >", "classmicrola_1_1KalmanFilter.html", null ],
    [ "microla::fusion::detail::MagMeasurementEvaluation< T >", "structmicrola_1_1fusion_1_1detail_1_1MagMeasurementEvaluation.html", null ],
    [ "microla::detail::make_index_sequence_impl< N, Is >", "structmicrola_1_1detail_1_1make__index__sequence__impl.html", null ],
    [ "microla::detail::make_index_sequence_impl< 0, Is... >", "structmicrola_1_1detail_1_1make__index__sequence__impl_3_010_00_01Is_8_8_8_01_4.html", null ],
    [ "microla::Mat< T, R, C >", "classmicrola_1_1Mat.html", null ],
    [ "microla::Mat< float, 1, 1 >", "classmicrola_1_1Mat.html", null ],
    [ "microla::Mat< float, 1, 2 >", "classmicrola_1_1Mat.html", null ],
    [ "microla::Mat< float, 2, 2 >", "classmicrola_1_1Mat.html", null ],
    [ "microla::Mat< T, 3, 3 >", "classmicrola_1_1Mat.html", null ],
    [ "microla::Mat< T, 6, 6 >", "classmicrola_1_1Mat.html", null ],
    [ "microla::mat_traits< T, R, C >", "structmicrola_1_1mat__traits.html", null ],
    [ "microla::resource_checks::MatDMACheck< T, R, C >", "structmicrola_1_1resource__checks_1_1MatDMACheck.html", null ],
    [ "microla::resource_checks::MatLayoutCheck< T, R, C >", "structmicrola_1_1resource__checks_1_1MatLayoutCheck.html", null ],
    [ "microla::MatrixView< T, R, C >", "classmicrola_1_1MatrixView.html", null ],
    [ "MatrixView< T, R, C >", "classMatrixView_3_01T_00_01R_00_01C_01_4.html", null ],
    [ "microla::resource_checks::MatSizeInfo< T, R, C >", "structmicrola_1_1resource__checks_1_1MatSizeInfo.html", null ],
    [ "microla::fusion::OrientationConfigBase< T >", "structmicrola_1_1fusion_1_1OrientationConfigBase.html", [
      [ "microla::fusion::DefaultAccelOnlyConfig< T >", "structmicrola_1_1fusion_1_1DefaultAccelOnlyConfig.html", null ],
      [ "microla::fusion::DefaultImu6EkfConfig< T >", "structmicrola_1_1fusion_1_1DefaultImu6EkfConfig.html", null ],
      [ "microla::fusion::DefaultImu6MahonyConfig< T >", "structmicrola_1_1fusion_1_1DefaultImu6MahonyConfig.html", null ],
      [ "microla::fusion::DefaultImu9EkfConfig< T >", "structmicrola_1_1fusion_1_1DefaultImu9EkfConfig.html", null ],
      [ "microla::fusion::DefaultImu9MahonyConfig< T >", "structmicrola_1_1fusion_1_1DefaultImu9MahonyConfig.html", null ],
      [ "microla::fusion::HighDynamicsAccelOnlyConfig< T >", "structmicrola_1_1fusion_1_1HighDynamicsAccelOnlyConfig.html", null ],
      [ "microla::fusion::HighDynamicsImu6MahonyConfig< T >", "structmicrola_1_1fusion_1_1HighDynamicsImu6MahonyConfig.html", null ],
      [ "microla::fusion::HighDynamicsImu9MahonyConfig< T >", "structmicrola_1_1fusion_1_1HighDynamicsImu9MahonyConfig.html", null ]
    ] ],
    [ "microla::fusion::OrientationEstimate< T >", "structmicrola_1_1fusion_1_1OrientationEstimate.html", null ],
    [ "microla::fusion::OrientationEstimator< T, Config >", "classmicrola_1_1fusion_1_1OrientationEstimator.html", null ],
    [ "microla::fusion::OrientationEstimator< T, LeftConfig >", "classmicrola_1_1fusion_1_1OrientationEstimator.html", null ],
    [ "microla::fusion::OrientationEstimator< T, RightConfig >", "classmicrola_1_1fusion_1_1OrientationEstimator.html", null ],
    [ "microla::geometry::Plane< T >", "structmicrola_1_1geometry_1_1Plane.html", null ],
    [ "microla::geometry::Plane< T >", "structmicrola_1_1geometry_1_1Plane.html", null ],
    [ "microla::Quaternion< T >", "classmicrola_1_1Quaternion.html", null ],
    [ "microla::Quaternion< T >", "classmicrola_1_1Quaternion.html", null ],
    [ "microla::resource_checks::QuaternionDMACheck< T >", "structmicrola_1_1resource__checks_1_1QuaternionDMACheck.html", null ],
    [ "microla::resource_checks::QuaternionLayoutCheck< T >", "structmicrola_1_1resource__checks_1_1QuaternionLayoutCheck.html", null ],
    [ "microla::resource_checks::QuaternionSizeInfo< T >", "structmicrola_1_1resource__checks_1_1QuaternionSizeInfo.html", null ],
    [ "microla::geometry::Ray< T >", "structmicrola_1_1geometry_1_1Ray.html", null ],
    [ "microla::fusion::RelativeAngleConfigBase< T >", "structmicrola_1_1fusion_1_1RelativeAngleConfigBase.html", [
      [ "microla::fusion::DefaultRelativeAngleConfig< T >", "structmicrola_1_1fusion_1_1DefaultRelativeAngleConfig.html", null ]
    ] ],
    [ "microla::fusion::RelativeAngleEstimator< T, LeftConfig, RightConfig, RelativeConfig >", "classmicrola_1_1fusion_1_1RelativeAngleEstimator.html", null ],
    [ "microla::fusion::RelativeAngleResult< T >", "structmicrola_1_1fusion_1_1RelativeAngleResult.html", null ],
    [ "microla::fusion::detail::SampleTraits< Sample >", "structmicrola_1_1fusion_1_1detail_1_1SampleTraits.html", null ],
    [ "microla::fusion::detail::SampleTraits< AccelSample< T > >", "structmicrola_1_1fusion_1_1detail_1_1SampleTraits_3_01AccelSample_3_01T_01_4_01_4.html", null ],
    [ "microla::fusion::detail::SampleTraits< Imu6Sample< T > >", "structmicrola_1_1fusion_1_1detail_1_1SampleTraits_3_01Imu6Sample_3_01T_01_4_01_4.html", null ],
    [ "microla::fusion::detail::SampleTraits< Imu9Sample< T > >", "structmicrola_1_1fusion_1_1detail_1_1SampleTraits_3_01Imu9Sample_3_01T_01_4_01_4.html", null ],
    [ "microla::fusion::detail::SampleType< T, Model >", "structmicrola_1_1fusion_1_1detail_1_1SampleType.html", null ],
    [ "microla::fusion::detail::SampleType< T, SensorModel::accel_only >", "structmicrola_1_1fusion_1_1detail_1_1SampleType_3_01T_00_01SensorModel_1_1accel__only_01_4.html", null ],
    [ "microla::fusion::detail::SampleType< T, SensorModel::imu6 >", "structmicrola_1_1fusion_1_1detail_1_1SampleType_3_01T_00_01SensorModel_1_1imu6_01_4.html", null ],
    [ "microla::fusion::detail::SampleType< T, SensorModel::imu9 >", "structmicrola_1_1fusion_1_1detail_1_1SampleType_3_01T_00_01SensorModel_1_1imu9_01_4.html", null ],
    [ "microla::fusion::ScalarAngleResult< T >", "structmicrola_1_1fusion_1_1ScalarAngleResult.html", null ],
    [ "microla::fusion::SensorCalibration< T >", "structmicrola_1_1fusion_1_1SensorCalibration.html", null ],
    [ "microla::geometry::Sphere< T >", "structmicrola_1_1geometry_1_1Sphere.html", null ],
    [ "microla::geometry::Triangle< T >", "structmicrola_1_1geometry_1_1Triangle.html", null ],
    [ "microla::Vec< T, N >", "classmicrola_1_1Vec.html", null ],
    [ "microla::Vec< float, 2 >", "classmicrola_1_1Vec.html", null ],
    [ "microla::Vec< float, 3 >", "classmicrola_1_1Vec.html", null ],
    [ "microla::Vec< T, 3 >", "classmicrola_1_1Vec.html", null ],
    [ "Vec< T, N >", "classVec_3_01T_00_01N_01_4.html", null ],
    [ "microla::resource_checks::VecDMACheck< T, N >", "structmicrola_1_1resource__checks_1_1VecDMACheck.html", null ],
    [ "microla::resource_checks::VecLayoutCheck< T, N >", "structmicrola_1_1resource__checks_1_1VecLayoutCheck.html", null ],
    [ "microla::resource_checks::VecSizeInfo< T, N >", "structmicrola_1_1resource__checks_1_1VecSizeInfo.html", null ],
    [ "microla::VectorView< T, N >", "classmicrola_1_1VectorView.html", null ],
    [ "microla::Version", "structmicrola_1_1Version.html", null ]
];